# Site settings
title: Fairwaves documentation
email: ""
description: > # this means to ignore newlines until "baseurl:"
  Documentation for Fairwaves' architecture, products and services 
baseurl: "/docs" # the subpath of your site, e.g. /blog/
url: "http://fairwaves.co" # the base hostname & protocol for your site
twitter_username: fairwaves
github_username:  fairwaves

# Build settings
markdown: kramdown
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author: "Fairwaves Inc"
      category: "Documentation"
